# Generated by Django 6.0.6 on 2026-07-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'budgettyreshed'", unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_mobile_normalized', models.CharField(help_text='Stored normalized (digits only, no leading 0/61). Set via the admin save hook or the add_contract management command — see save() below.', max_length=20)),
                ('contract_version', models.CharField(help_text='e.g. 2026-07-01-v1', max_length=50)),
                ('contract_html', models.TextField(help_text='Trusted HTML you author yourself — rendered with |safe. Never populate this from client-submitted input.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_typed', models.CharField(max_length=255)),
                ('signature_path', models.CharField(help_text='Relative path under SIGNATURES_DIR', max_length=255)),
                ('contract_version', models.CharField(max_length=50)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='contracts.contract')),
            ],
        ),
    ]
